version: '2'

services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  frontend:
    restart: always
    build: ./
    command: >
      bash -c "cd ./pubtrack/frontend && npm run serve"
    volumes:
      - ./:/code
    ports:
      - "8080:8080"

# Originally, the cookiecutter template also included a separate container to host the documentation, but we dont need
# that since the documentation is managed using RTD.
#  documentation:
#    restart: always
#    build: ./
#    command: "mkdocs serve"
#    volumes:
#      - ./:/code
#    ports:
#      - "8005:8001"
